CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY,
username TEXT UNIQUE NOT NULL,
email TEXT UNIQUE NOT NULL,
password_hash TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS decks (
id SERIAL PRIMARY KEY,
user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
title TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS cards (
id SERIAL PRIMARY KEY,
deck_id INTEGER NOT NULL REFERENCES decks(id) ON DELETE CASCADE,
front TEXT NOT NULL,
back TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS card_progress (
id SERIAL PRIMARY KEY,
card_id INTEGER NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
box_level INTEGER NOT NULL DEFAULT 1, 
last_reviewed TIMESTAMP,
next_review TIMESTAMP NOT NULL DEFAULT NOW(),
correct_count INTEGER NOT NULL DEFAULT 0,
incorrect_count INTEGER NOT NULL DEFAULT 0,
UNIQUE(card_id, user_id)
);